GPU: [0]

VERBOSE: True

#MODEL:
#  MODE: 'Deraining'
#  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 3
  NUM_EPOCHS: 1500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './dataset/ISTD/train'       # path to training data
  VAL_DIR: './dataset/ISTD/test' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images